name: Cargo Build & Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: trace

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Run tests - All features enabled
        run: |
          cargo build --verbose --all-features
          timeout 1m cargo test --verbose --all-features -- --nocapture
      - name: Run tests - No features enabled
        run: |
          cargo build --verbose --no-default-features --all-targets
          timeout 1m cargo test --verbose --no-default-features --all-targets -- --nocapture
      - if: ${{ matrix.toolchain == 'nightly' }}
        uses: taiki-e/install-action@nextest
      - name: Install Miri (nightly only)
        if: ${{ matrix.toolchain == 'nightly' }}
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - name: Run tests - Big endian target (nightly only)
        if: ${{ matrix.toolchain == 'nightly' }}
        run: cargo miri nextest run --target powerpc-unknown-linux-gnu --verbose

